local PROFILER = hash("profiler")

function init(self)
	msg.post(".", "acquire_input_focus")
	self.profiler = true
	profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)
end

function update(self, dt)
	collectgarbage()
end

function on_input(self, action_id, action)
	if action_id == PROFILER and action.released then
		profiler.enable_ui(self.profiler)
		self.profiler = not self.profiler
	end
end
